general:
  project_name: rsna_mammo
  input_path: ../../../data/input
  output_path: ../../data/output
  save_name: exp264_1024_640_aux_drop0.5_path0.3_over
  seed: &seed 42
  cv: true
  wandb_desabled: false
  fold: [0, 1, 2, 3] # list (0-idx start) or null. set one element list, hold-out mode.
  n_splits: 4

task:
  target: cancer
  aux_target: [site_id, laterality, view, implant, biopsy, invasive, BIRADS, density, difficult_negative_case, age] # machine_id
  aux_loss_weight: 1.0
  
  extend: png
  size: 1024
  bit: 8
  voi: true
  
  height_size: 1024
  width_size: 640

model:
  model_name: tf_efficientnetv2_s
  pretrained: true
  model_save: &model_save true
  save_weights_only: true
  grad_checkpointing: false
  
  drop_rate: 0.5
  drop_path_rate: 0.3
  aug_mix: false
  
  train_2nd: false
  epoch_2nd: 0
  
  in_chans: 3
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  
  early_stopping: null
  early_stopping_patience: null
  
  batch_balanced: weighted # oversampling, undersampling, weighted, null
  minor_weight: 0.125
  
  criterion: BCEWithLogitsLoss
  weighted_loss: null
  
  optimizer:
      name: Adam
      params:
        lr: 1.0e-4
        #weight_decay: 1.0e-2

  scheduler:
      #name: CosineAnnealingLR
      #params:
      #  T_max: 5
      #  eta_min: 1.0e-5
      name: OneCycleLR
      params:
        pct_start: 0.1
        div_factor: 1.0e+3
        max_lr: 1.0e-4
        epochs: 5
        
arcface: null
#  params:
#      in_features: 512
#      out_features: 2
#      s: 30.0
#      m: 0.5
#      easy_margin: True
#      ls_eps: 0.0

pl_params:
  max_epochs: 5
  accelerator: auto
  accumulate_grad_batches: 4
  precision: 16 # 16 or 32
  deterministic: true
  benchmark: false
  enable_checkpointing: *model_save
  enable_model_summary: false
  enable_progress_bar: true
  #gradient_clip_val: 1.
  #limit_train_batches: 0.01 # for debug
  #limit_val_batches: 0.01 # for debug

train_loader:
  batch_size: 8
  shuffle: true
  num_workers: 2
  pin_memory: true
  drop_last: true
valid_loader:
  batch_size: 8
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
test_loader:
  batch_size: 8
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
