general:
  project_name: rsna_mammo
  input_path: ../../data/input
  output_path: ../../data/output
  save_name: resnet18_test
  seed: &seed 42
  cv: true
  wandb_desabled: false
  fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  n_splits: 5

task:
  target: cancer
  extend: png
  
  height_size: 224
  width_size: 224

model:
  model_name: resnet18
  pretrained: true
  model_save: &model_save true
  
  in_chans: 3
  
  early_stopping: null
  early_stopping_patience: null
  
  criterion: BCEWithLogitsLoss
  
  optimizer:
      name: Adam
      params:
        lr: 1.0e-5
        #weight_decay: 1.0e-2

  scheduler:
      name: OneCycleLR
      params:
        pct_start: 0.1
        div_factor: 1.0e+3
        max_lr: 1.0e-5
        epochs: 5

pl_params:
  max_epochs: 5
  accelerator: auto
  accumulate_grad_batches: 1
  precision: 16 # 16 or 32
  deterministic: true
  benchmark: false
  enable_checkpointing: *model_save
  enable_model_summary: false
  enable_progress_bar: true
  #gradient_clip_val: 1.
  #limit_train_batches: 0.1 # for debug
  #limit_val_batches: 0.1 # for debug

train_loader:
  batch_size: 32
  shuffle: true
  num_workers: 2
  pin_memory: true
  drop_last: true
valid_loader:
  batch_size: 32
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
test_loader:
  batch_size: 32
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
